# file: mysql/tasks/databases.yml

- name: Echo database names to create
  debug: 
    msg: "mysql_databases = {{ mysql_databases }}"

- name: MySQL | Make sure the MySQL databases are present
  mysql_db:
    name: "{{ mysql_databases }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  when: mysql_databases|length > 0
